#!/usr/bin/env zsh

# Install OSX packages
if [[ `uname` == 'Darwin' ]]; then
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
fi

# install RVM because ruby <3
curl -sSL https://get.rvm.io | bash -s stable

# Install Vundler to manage Vim bundles
if [[ ! -d ~/.vim/bundle/vundle ]]; then
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi

# Symlink my vimrc
ln -s ./.vimrc $HOME/.vimrc

# Install bundles managed by Vundler
vim +BundleInstall +qall

# Install oh-my-zsh
curl -L http://install.ohmyz.sh | sh

# Install AAM to manage AWS accounts
curl -L https://raw.github.com/jlogsdon/aam/master/aam.sh > ~/.aam.sh

# Symlink my zshrc
ln -s ./.zshrc ~/.zshrc

