#!/usr/bin/env bash
# shebang'd to bash because zsh ain't come standard

set -e

# First, setup some directories I want
mkdir -p $HOME/personal
mkdir -p $HOME/src
mkdir -p $HOME/.config/powerline
touch $HOME/personal/dotfiles/.credentials

if [[ `uname` == Darwin* ]]; then
  echo "Installing is unsupported on this architecture"
  exit 1
fi

# Install base dependencies for everything
bash -l ./packages/base
zsh -l ./packages/zsh
zsh -l ./packages/st

# Next, install ASDF to manage, like, so many packages
zsh -l ./packages/asdf

. $HOME/.asdf/asdf.sh

zsh -l ./packages/asdf_langs

# Now do pip stuff because everyone loves python
zsh -l ./packages/pip_things

# Install neovim + plugins
zsh -l ./packages/neovim

# Install patched fonts for glyphs
zsh -l ./packages/fonts

# Install TEM
zsh -l ./packages/tem

# Install tmux
zsh -l ./packages/tmux

# Configure git
zsh -l ./packages/gitconfig

echo "Installed! Now set your font to Hack Regular to get glyphs"
